### ISSUE TITLE
Need to Specify Modules Version

### ISSUE THREAD

**Issue by HanXiao701** [colbyj/bride-of-frankensystem#25] opened 2023-10-04 11:55 UTC
Currently when trying to install the BOFS, as there are no specific module versions, some errors will occur as the latest version of modules has changed some attributes, like the errors I encountered below:
`cannot import name 'url_quote' from "'werkzeug.urls'"`
`module 'dns.rdtypes' has no attribute 'ANY'`
`cannot import name '_app_ctx_stack' from 'flask. globals`

I found this by specifying the following module versions in the dependencies of pyproject.toml could solve this problem:
```
"flask==2.1.3",
"eventlet==0.33.1",
"sqlalchemy==1.4.39",
"flask-sqlalchemy==2.5.1",
"Werkzeug==2.2.0",
"dnspython==2.2.1",
```

**Comment by colbyj** [comment] 2023-10-04 18:03
Thanks for sharing this! It looks like this error is fixed in newer versions of Flask (2.3.x or higher). In general, I'd like to ensure BOF is compatible with the latest version of all the modules rather than sticking with an older release. 

I just made a BOF project of my own with the following requirements, and it worked as intended:

```
blinker==1.6.2
bride-of-frankensystem==1.9.2
Brotli==1.1.0
click==8.1.7
colorama==0.4.6
dnspython==2.4.2
eventlet==0.33.3
Flask==2.3.3
Flask-Compress==1.14
Flask-SQLAlchemy==3.1.1
greenlet==2.0.2
itsdangerous==2.1.2
Jinja2==3.1.2
MarkupSafe==2.1.3
six==1.16.0
SQLAlchemy==2.0.21
toml==0.10.2
typing_extensions==4.8.0
Werkzeug==2.3.7
```

**Comment by HanXiao701** [comment] 2023-10-04 18:05
Thanks for letting me know, I will try the new version of modules.

**Comment by colbyj** [comment] 2023-10-04 20:09
I pushed a new version to pip (labelled 1.9.2.1) that is configured to require Flask >= 2.3.0. `pip install bride-of-frankensystem` should hopefully resolve any issues you have with versions. (or `pip install bride-of-frankensystem --upgrade` if it's installed already).

**Closed as completed** 2023-10-06 07:28 UTC
